# Generated by Django 2.2 on 2019-11-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinDoseMapResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phantom_width', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('phantom_height', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('phantom_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('patient_mass', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('patient_mass_assumed', models.CharField(blank=True, max_length=16, null=True)),
                ('patient_size', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('patient_size_assumed', models.CharField(blank=True, max_length=16, null=True)),
                ('patient_orientation', models.CharField(blank=True, max_length=16, null=True)),
                ('patient_orientation_assumed', models.CharField(blank=True, max_length=16, null=True)),
                ('peak_skin_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('skin_map_version', models.CharField(blank=True, max_length=16, null=True)),
                ('general_study_module_attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remapp.GeneralStudyModuleAttr')),
            ],
        ),
    ]
