# Generated by Django 2.2 on 2019-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remapp', '0003_skindosemapresults_hit_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindosemapresults',
            name='dap_percentage_contributed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
    ]
